### ISSUE TITLE
Flagged as infected

### ISSUE THREAD

**Issue by kibade** [screeneroner/Caffeine#1]
This could be a false positive, but I wanted you to know this is happening.
I uploaded the caffeine.exe to this site after Avast flagged this as infected:
https://www.virustotal.com/gui/home/upload

Here was my result implying there is a problem:
Popular threat label
[trojan.]
Threat categories
[trojan]

Security vendors' analysis
AhnLab-V3
Malware/Win.Generic.C4642984
Antiy-AVL
Trojan/Win64.Generic
Bkav Pro
W64.AIDetectMalware
Ikarus
HackTool.PEPatch
Jiangmin
Trojan.PSW.Disco.bsk
MaxSecure
Trojan.Malware.300983.susgen

**Comment by screeneroner** [comment]
Thanks a lot for warning me. However, I'm constantly using the Comodo Antivirus and keep it refreshed every 6 hours. So, you may be right - it CAN be a real false positive alert. Especially considering the very unusual environment where this app was created. Keyboard hooks... keystroke emulators... a lot of AVs treating such parts of codes as suspicious 'by default'. If you are still afraid using my exe - you can build your own one by compiling provided source with the original compiler that you can download from genuine Autohotkey site.
Regards and thank you for your vigilance!

**Comment by screeneroner** [comment]
Hope I can close this issue. If you find anything else that worth my attention - please let me know.
